
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Tech Contracting"
theme = "khata"
[params.author]
  profilePhoto = "./images/workerbee.jpg"

  

buildDrafts = true

[menu]

  [[menu.main]]
    identifier = "Home"
    name = "Home"
    title = "Home"
    url = "/"
  [[menu."Resources"]]
    identifier = "Resources"
    name = "Resources"
    title = "Resources"
    url = "/resources/"
  [[menu."Know Your Rights"]]
    identifier = "Know Your Rights"
    name = "Know Your Rights"
    title = "Know Your Rights"
    url = "/rights/"



