
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Tech Contracting"
theme = "khata"
[params.author]
  profilePhoto = "https://i.ytimg.com/vi/tJdgErAfiRQ/maxresdefault.jpg"

  

buildDrafts = true

[menu]

  [[menu.main]]
    identifier = "Home"
    name = "Home"
    title = "Home"
    url = "/"
  [[menu.resources]]
    identifier = "Resources"
    name = "Resources"
    title = "Resources"
    url = "/resources/"
  [[menu.kyr]]
    identifier = "Know Your Rights"
    name = "Know Your Rights"
    title = "Know Your Rights"
    url = "/kyr/"


